In [1]:
import soccerdata as sd
from pathlib import PosixPath
import pandas as pd
import numpy as np

[07/06/23 10:56:08] INFO     Custom team name replacements loaded from                                ]8;id=157352;file:///home/morten/.conda/envs/packing-report/lib/python3.10/site-packages/soccerdata/_config.py\_config.py]8;;\:]8;id=523771;file:///home/morten/.conda/envs/packing-report/lib/python3.10/site-packages/soccerdata/_config.py#83\83]8;;\
                             /home/morten/soccerdata/config/teamname_replacements.json.

                    INFO     Custom league dict loaded from                                          ]8;id=363640;file:///home/morten/.conda/envs/packing-report/lib/python3.10/site-packages/soccerdata/_config.py\_config.py]8;;\:]8;id=157314;file:///home/morten/.conda/envs/packing-report/lib/python3.10/site-packages/soccerdata/_config.py#157\157]8;;\
                             /home/morten/soccerdata/config/league_dict.json.

In [7]:
def get_goal_dict(event_dataframe):
    event_dataframe = event_dataframe[event_dataframe["type"] == "Goal"]
    goal_dict = {"time": event_dataframe["expanded_minute"].values, "team": event_dataframe["team_id"].values}
    return goal_dict

In [2]:
ws = sd.WhoScored(
    #  "GER-Bundesliga", "GER-Bundesliga2", "ENG-Premier League", "ESP-La Liga", "FRA-Ligue 1", "ITA-Serie A"
    leagues=["GER-Bundesliga2"],
    seasons=[21],
    no_cache=False,
    no_store=False,
    data_dir=PosixPath("/home/morten/Develop/Open-Data/soccerdata"),
    path_to_browser="/usr/bin/chromium",
    headless=False,
)

[07/06/23 10:56:11] INFO     Saving cached data to /home/morten/Develop/Open-Data/soccerdata          ]8;id=633890;file:///home/morten/.conda/envs/packing-report/lib/python3.10/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=847309;file:///home/morten/.conda/envs/packing-report/lib/python3.10/site-packages/soccerdata/_common.py#89\89]8;;\

[07/06/23 10:56:12] INFO     patching driver executable                                              ]8;id=460152;file:///home/morten/.conda/envs/packing-report/lib/python3.10/site-packages/undetected_chromedriver/patcher.py\patcher.py]8;;\:]8;id=554500;file:///home/morten/.conda/envs/packing-report/lib/python3.10/site-packages/undetected_chromedriver/patcher.py#231\231]8;;\
                             /home/morten/.local/share/undetected_chromedriver/4a3fda21354d51c6_chro
                             medriver

In [3]:
schedule = ws.read_schedule()
schedule.head()

[07/06/23 10:56:16] INFO     Retrieving game schedule of GER-Bundesliga2 - 2122 from the cache     ]8;id=258062;file:///home/morten/.conda/envs/packing-report/lib/python3.10/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=757093;file:///home/morten/.conda/envs/packing-report/lib/python3.10/site-packages/soccerdata/whoscored.py#391\391]8;;\

                                                                             date  \
league          season game
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg             2021-07-23 19:30:00
                       2021-07-24 Darmstadt-Jahn Regensburg   2021-07-24 12:30:00
                       2021-07-24 Dynamo Dresden-Ingolstadt   2021-07-24 12:30:00
                       2021-07-24 FC Heidenheim-Paderborn     2021-07-24 12:30:00
                       2021-07-24 Hansa Rostock-Karlsruher SC 2021-07-24 12:30:00

                                                                    home_team  \
league          season game
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg                     Schalke
                       2021-07-24 Darmstadt-Jahn Regensburg         Darmstadt
                       2021-07-24 Dynamo Dresden-Ingolstadt    Dynamo Dresden
                       2021-07-24 FC Heidenheim-Paderborn       FC Heidenheim
                       2021-07-24 Hansa Rostock-Karlsruher SC   Hansa Rostock

                                                                     away_team  \
league          season game
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg                      Hamburg
                       2021-07-24 Darmstadt-Jahn Regensburg    Jahn Regensburg
                       2021-07-24 Dynamo Dresden-Ingolstadt         Ingolstadt
                       2021-07-24 FC Heidenheim-Paderborn            Paderborn
                       2021-07-24 Hansa Rostock-Karlsruher SC    Karlsruher SC

                                                               game_id  \
league          season game
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg              1557679
                       2021-07-24 Darmstadt-Jahn Regensburg    1557630
                       2021-07-24 Dynamo Dresden-Ingolstadt    1557636
                       2021-07-24 FC Heidenheim-Paderborn      1557631
                       2021-07-24 Hansa Rostock-Karlsruher SC  1557635

                                                                                                             url  \
league          season game
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg              https://www.whoscored.com/Matches/1557679/Live...
                       2021-07-24 Darmstadt-Jahn Regensburg    https://www.whoscored.com/Matches/1557630/Live...
                       2021-07-24 Dynamo Dresden-Ingolstadt    https://www.whoscored.com/Matches/1557636/Live...
                       2021-07-24 FC Heidenheim-Paderborn      https://www.whoscored.com/Matches/1557631/Live...
                       2021-07-24 Hansa Rostock-Karlsruher SC  https://www.whoscored.com/Matches/1557635/Live...

                                                               stage
league          season game
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg                NaN
                       2021-07-24 Darmstadt-Jahn Regensburg      NaN
                       2021-07-24 Dynamo Dresden-Ingolstadt      NaN
                       2021-07-24 FC Heidenheim-Paderborn        NaN
                       2021-07-24 Hansa Rostock-Karlsruher SC    NaN

In [4]:
events = ws.read_events(match_id=1557679)

[07/06/23 10:56:20] INFO     Retrieving game schedule of GER-Bundesliga2 - 2122 from the cache     ]8;id=732627;file:///home/morten/.conda/envs/packing-report/lib/python3.10/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=757233;file:///home/morten/.conda/envs/packing-report/lib/python3.10/site-packages/soccerdata/whoscored.py#391\391]8;;\

                    INFO     [1/1] Retrieving game with id=1557679                                 ]8;id=765367;file:///home/morten/.conda/envs/packing-report/lib/python3.10/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=356528;file:///home/morten/.conda/envs/packing-report/lib/python3.10/site-packages/soccerdata/whoscored.py#640\640]8;;\

In [5]:
events["type"].unique()

array(['FormationSet', 'Start', 'Pass', 'Interception', 'BallRecovery',
       'BlockedPass', 'Clearance', 'BallTouch', 'Dispossessed', 'Tackle',
       'Aerial', 'KeeperPickup', 'Foul', 'Challenge', 'TakeOn',
       'MissedShots', 'Goal', 'CornerAwarded', 'Save', 'SavedShot',
       'PenaltyFaced', 'SubstitutionOff', 'SubstitutionOn', 'Card',
       'ShieldBallOpp', 'FormationChange', 'End'], dtype=object)

In [50]:
event_end = events.loc[(events["type"] == "End")]
END_OF_GAME = event_end[(event_end["period"] == "SecondHalf") &  (event_end["team_id"] == 39)]["expanded_minute"].values[0]
event_end

                                                              game_id  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312475659  1557679
                                                  2312475661  1557679
                                                  2312489569  1557679
                                                  2312489571  1557679
                                                  2312489593  1557679
                                                  2312489597  1557679

                                                                  period  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312475659   FirstHalf
                                                  2312475661   FirstHalf
                                                  2312489569  SecondHalf
                                                  2312489571  SecondHalf
                                                  2312489593    PostGame
                                                  2312489597    PostGame

                                                              minute  second  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312475659      48      51
                                                  2312475661      48      51
                                                  2312489569      93       4
                                                  2312489571      93       4
                                                  2312489593       0       0
                                                  2312489597       0       0

                                                              expanded_minute  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312475659               48
                                                  2312475661               48
                                                  2312489569               97
                                                  2312489571               97
                                                  2312489593                7
                                                  2312489597                7

                                                             type  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312475659  End
                                                  2312475661  End
                                                  2312489569  End
                                                  2312489571  End
                                                  2312489593  End
                                                  2312489597  End

                                                             outcome_type  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312475659   Successful
                                                  2312475661   Successful
                                                  2312489569   Successful
                                                  2312489571   Successful
                                                  2312489593   Successful
                                                  2312489597   Successful

                                                              team_id  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312475659       38
                                                  2312475661       39
                                                  2312489569       39
                                                  2312489571       38
                                                  2312489593       39
                                                  2312489597       38

                                                                 team  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312475659  Hamburg
                                                  2312475661  Schalke
                                                  2312489569  Schalke
                                                  2312489571  Hamburg
                                                  2312489593  Schalke
                                                  2312489597  Hamburg

                                                              player_id  ...  \
league          season game                       id                     ...
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312475659        NaN  ...
                                                  2312475661        NaN  ...
                                                  2312489569        NaN  ...
                                                  2312489571        NaN  ...
                                                  2312489593        NaN  ...
                                                  2312489597        NaN  ...

                                                             goal_mouth_z  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312475659          NaN
                                                  2312475661          NaN
                                                  2312489569          NaN
                                                  2312489571          NaN
                                                  2312489593          NaN
                                                  2312489597          NaN

                                                              blocked_x  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312475659        NaN
                                                  2312475661        NaN
                                                  2312489569        NaN
                                                  2312489571        NaN
                                                  2312489593        NaN
                                                  2312489597        NaN

                                                              blocked_y  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312475659        NaN
                                                  2312475661        NaN
                                                  2312489569        NaN
                                                  2312489571        NaN
                                                  2312489593        NaN
                                                  2312489597        NaN

                                                              qualifiers  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312475659          []
                                                  2312475661          []
                                                  2312489569          []
                                                  2312489571          []
                                                  2312489593          []
                                                  2312489597          []

                                                              is_touch  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312475659     False
                                                  2312475661     False
                                                  2312489569     False
                                                  2312489571     False
                                                  2312489593     False
                                                  2312489597     False

                                                              is_shot  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312475659      NaN
                                                  2312475661      NaN
                                                  2312489569      NaN
                                                  2312489571      NaN
                                                  2312489593      NaN
                                                  2312489597      NaN

                                                              is_goal  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312475659      NaN
                                                  2312475661      NaN
                                                  2312489569      NaN
                                                  2312489571      NaN
                                                  2312489593      NaN
                                                  2312489597      NaN

                                                              card_type  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312475659        NaN
                                                  2312475661        NaN
                                                  2312489569        NaN
                                                  2312489571        NaN
                                                  2312489593        NaN
                                                  2312489597        NaN

                                                              related_event_id  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312475659               NaN
                                                  2312475661               NaN
                                                  2312489569               NaN
                                                  2312489571               NaN
                                                  2312489593               NaN
                                                  2312489597               NaN

                                                             related_player_id
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312475659               NaN
                                                  2312475661               NaN
                                                  2312489569               NaN
                                                  2312489571               NaN
                                                  2312489593               NaN
                                                  2312489597               NaN

[6 rows x 26 columns]

In [6]:
goal_dataframe = events.loc[(events["type"] == "Goal")]
goal_dataframe

                                                              game_id  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312463541  1557679
                                                  2312480707  1557679
                                                  2312488091  1557679
                                                  2312488843  1557679

                                                                  period  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312463541   FirstHalf
                                                  2312480707  SecondHalf
                                                  2312488091  SecondHalf
                                                  2312488843  SecondHalf

                                                              minute  second  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312463541       6      37
                                                  2312480707      52      33
                                                  2312488091      85      40
                                                  2312488843      89      23

                                                              expanded_minute  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312463541                6
                                                  2312480707               56
                                                  2312488091               89
                                                  2312488843               93

                                                              type  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312463541  Goal
                                                  2312480707  Goal
                                                  2312488091  Goal
                                                  2312488843  Goal

                                                             outcome_type  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312463541   Successful
                                                  2312480707   Successful
                                                  2312488091   Successful
                                                  2312488843   Successful

                                                              team_id  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312463541       39
                                                  2312480707       38
                                                  2312488091       38
                                                  2312488843       38

                                                                 team  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312463541  Schalke
                                                  2312480707  Hamburg
                                                  2312488091  Hamburg
                                                  2312488843  Hamburg

                                                              player_id  ...  \
league          season game                       id                     ...
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312463541    30464.0  ...
                                                  2312480707   136707.0  ...
                                                  2312488091   280720.0  ...
                                                  2312488843   329689.0  ...

                                                             goal_mouth_z  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312463541          8.9
                                                  2312480707          8.9
                                                  2312488091          3.8
                                                  2312488843         27.2

                                                              blocked_x  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312463541        NaN
                                                  2312480707        NaN
                                                  2312488091        NaN
                                                  2312488843        NaN

                                                              blocked_y  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312463541        NaN
                                                  2312480707        NaN
                                                  2312488091        NaN
                                                  2312488843        NaN

                                                                                                     qualifiers  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312463541  [{'type': {'displayName': 'Assisted', 'value':...
                                                  2312480707  [{'type': {'displayName': 'BigChance', 'value'...
                                                  2312488091  [{'type': {'displayName': 'BoxCentre', 'value'...
                                                  2312488843  [{'type': {'displayName': 'GoalMouthY', 'value...

                                                              is_touch  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312463541      True
                                                  2312480707      True
                                                  2312488091      True
                                                  2312488843      True

                                                              is_shot  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312463541     True
                                                  2312480707     True
                                                  2312488091     True
                                                  2312488843     True

                                                              is_goal  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312463541     True
                                                  2312480707     True
                                                  2312488091     True
                                                  2312488843     True

                                                              card_type  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312463541        NaN
                                                  2312480707        NaN
                                                  2312488091        NaN
                                                  2312488843        NaN

                                                              related_event_id  \
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312463541              62.0
                                                  2312480707               NaN
                                                  2312488091             975.0
                                                  2312488843             992.0

                                                             related_player_id
league          season game                       id
GER-Bundesliga2 2122   2021-07-23 Schalke-Hamburg 2312463541          361419.0
                                                  2312480707               NaN
                                                  2312488091          419916.0
                                                  2312488843           90966.0

[4 rows x 26 columns]

In [10]:
loader = ws.read_events(match_id=1557679, output_fmt='loader')

[07/06/23 10:58:27] INFO     Retrieving game schedule of GER-Bundesliga2 - 2122 from the cache     ]8;id=682636;file:///home/morten/.conda/envs/packing-report/lib/python3.10/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=4887;file:///home/morten/.conda/envs/packing-report/lib/python3.10/site-packages/soccerdata/whoscored.py#391\391]8;;\

                    INFO     [1/1] Retrieving game with id=1557679                                 ]8;id=937631;file:///home/morten/.conda/envs/packing-report/lib/python3.10/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=838811;file:///home/morten/.conda/envs/packing-report/lib/python3.10/site-packages/soccerdata/whoscored.py#640\640]8;;\

In [8]:
def get_player_minutes_dict(loader_players_df, events):
    loader_players_df = loader_players_df[loader_players_df["is_starter"] == True]
    players = np.swapaxes([loader_players_df["player_id"].values, loader_players_df["team_id"].values,
               [0 for _ in range(len(loader_players_df["player_id"].values))], [-1 for _ in range(len(loader_players_df["player_id"].values))]], 0, 1)
    sub_dataframe = events.loc[(events["type"] == "SubstitutionOn") | (events["type"] == "SubstitutionOff")]
    on_dataframe = sub_dataframe.loc[(sub_dataframe["type"] == "SubstitutionOn")].copy()
    # on_dataframe["time_in_seconds"] = (on_dataframe["minute"] * 60) + on_dataframe["second"]
    on_players = np.swapaxes([on_dataframe["player_id"].values.astype(int), on_dataframe["team_id"].values,
               on_dataframe["expanded_minute"].values, [-1 for _ in range(len(on_dataframe["player_id"].values))]], 0, 1)
    players_dict = {}
    for starter in [*players,*on_players]:
        players_dict[starter[0]] = {}
        players_dict[starter[0]]["team_id"] = starter[1]
        players_dict[starter[0]]["on"] = starter[2]
        players_dict[starter[0]]["off"] = starter[3]

    off_dataframe = sub_dataframe.loc[(sub_dataframe["type"] == "SubstitutionOff")].copy()
    # off_dataframe["time_in_seconds"] = (off_dataframe["minute"] * 60) + off_dataframe["second"]
    off_players = np.swapaxes([off_dataframe["player_id"].values.astype(int), off_dataframe["expanded_minute"].values], 0, 1)
    for sub_off in off_players:
        players_dict[sub_off[0]]["off"] = sub_off[1]

    return players_dict

In [11]:
loader_players_df = loader.players(1557679)

In [12]:
get_goal_dict(events)

{'time': array([ 6, 56, 89, 93]), 'team': array([39, 38, 38, 38])}

In [25]:
get_player_minutes_dict(loader_players_df, events)

{13765: {'team_id': 39, 'on': 0, 'off': -1},
 393355: {'team_id': 39, 'on': 0, 'off': -1},
 411279: {'team_id': 39, 'on': 0, 'off': 59},
 82628: {'team_id': 39, 'on': 0, 'off': -1},
 383806: {'team_id': 39, 'on': 0, 'off': -1},
 301027: {'team_id': 39, 'on': 0, 'off': -1},
 70227: {'team_id': 39, 'on': 0, 'off': 31},
 83804: {'team_id': 39, 'on': 0, 'off': 76},
 70162: {'team_id': 39, 'on': 0, 'off': -1},
 361419: {'team_id': 39, 'on': 0, 'off': -1},
 30464: {'team_id': 39, 'on': 0, 'off': -1},
 132896: {'team_id': 38, 'on': 0, 'off': -1},
 132011: {'team_id': 38, 'on': 0, 'off': -1},
 361253: {'team_id': 38, 'on': 0, 'off': -1},
 129751: {'team_id': 38, 'on': 0, 'off': -1},
 140849: {'team_id': 38, 'on': 0, 'off': -1},
 243758: {'team_id': 38, 'on': 0, 'off': 74},
 121975: {'team_id': 38, 'on': 0, 'off': -1},
 343436: {'team_id': 38, 'on': 0, 'off': 70},
 329689: {'team_id': 38, 'on': 0, 'off': -1},
 347773: {'team_id': 38, 'on': 0, 'off': 81},
 136707: {'team_id': 38, 'on': 0, 'off': 81},
 415639: {'team_id': 39, 'on': 31, 'off': -1},
 323169: {'team_id': 39, 'on': 59, 'off': -1},
 280720: {'team_id': 38, 'on': 70, 'off': -1},
 419916: {'team_id': 38, 'on': 74, 'off': -1},
 419915: {'team_id': 39, 'on': 76, 'off': -1},
 392643: {'team_id': 38, 'on': 81, 'off': -1},
 90966: {'team_id': 38, 'on': 81, 'off': -1}}

In [44]:
def get_corners_per_player(corner_dict, player_dict):
    player_corner = {}
    for player_id in player_dict:
        minutes = END_OF_GAME if ((player_dict[player_id]["off"] == -1) and (player_dict[player_id]["on"] == 0)) else (int(END_OF_GAME - (player_dict[player_id]["on"]))) if (player_dict[player_id]["off"] == -1) and (player_dict[player_id]["on"] != 0 ) else (int((player_dict[player_id]["off"] - player_dict[player_id]["on"])))
        player_corner[player_id] = {"team_id": player_dict[player_id]["team_id"], "for" : 0, "against": 0, "minutes": minutes}
        index_on = next(x[0] for x in enumerate(corner_dict["time"]) if x[1] > player_dict[player_id]["on"])
        index_off = len(corner_dict["time"]) if (player_dict[player_id]["off"] == -1) else next(x[0] for x in enumerate(corner_dict["time"]) if x[1] > player_dict[player_id]["off"]) 
        for index in range(index_on, index_off):
            if corner_dict["team"][index] == player_corner[player_id]["team_id"]:
                player_corner[player_id]["for"] += 1
            else:
                player_corner[player_id]["against"] += 1

    return player_corner

In [45]:
cpp = get_corners_per_player(get_corner_dict(events), get_player_minutes_dict(loader_players_df, events))

In [46]:
elo_player = {}
for player in cpp:
    # create test elo dict
    elo_player[player] = 1000

In [47]:
average_corners_home = [4, 6]
average_corners_away = [3, 6]

In [48]:
cpp

{13765: {'team_id': 39, 'for': 3, 'against': 5, 'minutes': 97},
 393355: {'team_id': 39, 'for': 3, 'against': 5, 'minutes': 97},
 411279: {'team_id': 39, 'for': 0, 'against': 4, 'minutes': 59},
 82628: {'team_id': 39, 'for': 3, 'against': 5, 'minutes': 97},
 383806: {'team_id': 39, 'for': 3, 'against': 5, 'minutes': 97},
 301027: {'team_id': 39, 'for': 3, 'against': 5, 'minutes': 97},
 70227: {'team_id': 39, 'for': 0, 'against': 3, 'minutes': 31},
 83804: {'team_id': 39, 'for': 1, 'against': 5, 'minutes': 76},
 70162: {'team_id': 39, 'for': 3, 'against': 5, 'minutes': 97},
 361419: {'team_id': 39, 'for': 3, 'against': 5, 'minutes': 97},
 30464: {'team_id': 39, 'for': 3, 'against': 5, 'minutes': 97},
 132896: {'team_id': 38, 'for': 5, 'against': 3, 'minutes': 97},
 132011: {'team_id': 38, 'for': 5, 'against': 3, 'minutes': 97},
 361253: {'team_id': 38, 'for': 5, 'against': 3, 'minutes': 97},
 129751: {'team_id': 38, 'for': 5, 'against': 3, 'minutes': 97},
 140849: {'team_id': 38, 'for': 5, 'against': 3, 'minutes': 97},
 243758: {'team_id': 38, 'for': 5, 'against': 1, 'minutes': 74},
 121975: {'team_id': 38, 'for': 5, 'against': 3, 'minutes': 97},
 343436: {'team_id': 38, 'for': 5, 'against': 1, 'minutes': 70},
 329689: {'team_id': 38, 'for': 5, 'against': 3, 'minutes': 97},
 347773: {'team_id': 38, 'for': 5, 'against': 1, 'minutes': 81},
 136707: {'team_id': 38, 'for': 5, 'against': 1, 'minutes': 81},
 415639: {'team_id': 39, 'for': 3, 'against': 2, 'minutes': 66},
 323169: {'team_id': 39, 'for': 3, 'against': 1, 'minutes': 38},
 280720: {'team_id': 38, 'for': 0, 'against': 2, 'minutes': 27},
 419916: {'team_id': 38, 'for': 0, 'against': 2, 'minutes': 23},
 419915: {'team_id': 39, 'for': 2, 'against': 0, 'minutes': 21},
 392643: {'team_id': 38, 'for': 0, 'against': 2, 'minutes': 16},
 90966: {'team_id': 38, 'for': 0, 'against': 2, 'minutes': 16}}

In [18]:
def corner_game_off(cpp, p_id, home):
    max_average_corner = max(average_corners_home) if home else max(average_corners_away)
    min_average_corner = min(average_corners_home) if home else min(average_corners_away)
    corners_per_90 = (cpp[p_id]["for"] / cpp[p_id]["minutes"]) * 90
    if corners_per_90 < min_average_corner:
        return 0
    elif corners_per_90 > max_average_corner:
        return 1
    else:
        return 0.5

def corner_game_def(cpp, p_id, home):
    max_average_corner = max(average_corners_home) if home else max(average_corners_away)
    min_average_corner = min(average_corners_home) if home else min(average_corners_away)
    corners_per_90 = (cpp[p_id]["for"] / cpp[p_id]["minutes"]) * 90
    if corners_per_90 > min_average_corner:
        return 0
    elif corners_per_90 < max_average_corner:
        return 1
    else:
        return 0.5

In [19]:
def update_elo(r_a, r_b, corner_game, K=35):
    R_a = pow(10, (r_a / 400))
    R_b = pow(10, (r_b / 400))
    E_a = R_a / (R_a + R_b)
    E_b = R_b / (R_a + R_b)
    S_a = corner_game # define result
    S_b = 1 - S_a
    r_strich_a = r_a + K * (S_a - E_a)
    r_strich_b = r_b + K * (S_b - E_b)

    print(r_strich_a, r_strich_b)

In [20]:
update_elo(1500, 1000, 0)

1466.8634075320708 1033.1365924679292

In [103]:
# create dataframe 
class GameTimeline:
    def __init__(self, player_min_dict) -> None:
        timelines = []
        for player in player_min_dict:
            # get player elo
            player_elo = np.random.randint(600, 1500) # fill with real elo value
            
            player_timeline = np.empty(END_OF_GAME + 3) # + 2 for id and team id, +1 for index of last minute
            player_timeline[:] = np.nan
            player_timeline[0] = player
            player_timeline[1] = player_min_dict[player]["team_id"]
            player_on = player_min_dict[player]["on"] + 2
            player_off = (player_min_dict[player]["off"] + 2) if player_min_dict[player]["off"] != -1 else END_OF_GAME + 3
            player_timeline[player_on : player_off] = player_elo
            timelines.append(player_timeline)
        
        self.game_timeline = pd.DataFrame(timelines, columns=["id", "team_id", *np.arange(END_OF_GAME + 1).astype(str)])

    def get_timeline(self):
        return self.game_timeline

# {13765: {'team_id': 39, 'on': 0, 'off': -1},
#  393355: {'team_id': 39, 'on': 0, 'off': -1},
#  411279: {'team_id': 39, 'on': 0, 'off': 59},
#  82628: {'team_id': 39, 'on': 0, 'off': -1},
#  383806: {'team_id': 39, 'on': 0, 'off': -1},
#  301027: {'team_id': 39, 'on': 0, 'off': -1},
#  70227: {'team_id': 39, 'on': 0, 'off': 31},
#  83804: {'team_id': 39, 'on': 0, 'off': 76},
#  70162: {'team_id': 39, 'on': 0, 'off': -1},
#  361419: {'team_id': 39, 'on': 0, 'off': -1},
#  30464: {'team_id': 39, 'on': 0, 'off': -1},
#  132896: {'team_id': 38, 'on': 0, 'off': -1},
#  132011: {'team_id': 38, 'on': 0, 'off': -1},
#  361253: {'team_id': 38, 'on': 0, 'off': -1},
#  129751: {'team_id': 38, 'on': 0, 'off': -1},
#  140849: {'team_id': 38, 'on': 0, 'off': -1},
#  243758: {'team_id': 38, 'on': 0, 'off': 74},
#  121975: {'team_id': 38, 'on': 0, 'off': -1},
#  343436: {'team_id': 38, 'on': 0, 'off': 70},
#  329689: {'team_id': 38, 'on': 0, 'off': -1},
#  347773: {'team_id': 38, 'on': 0, 'off': 81},
#  136707: {'team_id': 38, 'on': 0, 'off': 81},
#  415639: {'team_id': 39, 'on': 31, 'off': -1},
#  323169: {'team_id': 39, 'on': 59, 'off': -1},
#  280720: {'team_id': 38, 'on': 70, 'off': -1},
#  419916: {'team_id': 38, 'on': 74, 'off': -1},
#  419915: {'team_id': 39, 'on': 76, 'off': -1},
#  392643: {'team_id': 38, 'on': 81, 'off': -1},
#  90966: {'team_id': 38, 'on': 81, 'off': -1}}

In [104]:
gt = GameTimeline(get_player_minutes_dict(loader_players_df, events))

In [105]:
timeline = gt.get_timeline()
timeline

,id,team_id,0,1,2,3,4,5,6,7,...,88,89,90,91,92,93,94,95,96,97
0,13765.0,39.0,748.0,748.0,748.0,748.0,748.0,748.0,748.0,748.0,...,748.0,748.0,748.0,748.0,748.0,748.0,748.0,748.0,748.0,748.0
1,393355.0,39.0,1425.0,1425.0,1425.0,1425.0,1425.0,1425.0,1425.0,1425.0,...,1425.0,1425.0,1425.0,1425.0,1425.0,1425.0,1425.0,1425.0,1425.0,1425.0
2,411279.0,39.0,1010.0,1010.0,1010.0,1010.0,1010.0,1010.0,1010.0,1010.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,82628.0,39.0,1179.0,1179.0,1179.0,1179.0,1179.0,1179.0,1179.0,1179.0,...,1179.0,1179.0,1179.0,1179.0,1179.0,1179.0,1179.0,1179.0,1179.0,1179.0
4,383806.0,39.0,1430.0,1430.0,1430.0,1430.0,1430.0,1430.0,1430.0,1430.0,...,1430.0,1430.0,1430.0,1430.0,1430.0,1430.0,1430.0,1430.0,1430.0,1430.0
5,301027.0,39.0,1082.0,1082.0,1082.0,1082.0,1082.0,1082.0,1082.0,1082.0,...,1082.0,1082.0,1082.0,1082.0,1082.0,1082.0,1082.0,1082.0,1082.0,1082.0
6,70227.0,39.0,988.0,988.0,988.0,988.0,988.0,988.0,988.0,988.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,83804.0,39.0,837.0,837.0,837.0,837.0,837.0,837.0,837.0,837.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,70162.0,39.0,1048.0,1048.0,1048.0,1048.0,1048.0,1048.0,1048.0,1048.0,...,1048.0,1048.0,1048.0,1048.0,1048.0,1048.0,1048.0,1048.0,1048.0,1048.0
9,361419.0,39.0,974.0,974.0,974.0,974.0,974.0,974.0,974.0,974.0,...,974.0,974.0,974.0,974.0,974.0,974.0,974.0,974.0,974.0,974.0
10,30464.0,39.0,607.0,607.0,607.0,607.0,607.0,607.0,607.0,607.0,...,607.0,607.0,607.0,607.0,607.0,607.0,607.0,607.0,607.0,607.0
11,132896.0,38.0,1394.0,1394.0,1394.0,1394.0,1394.0,1394.0,1394.0,1394.0,...,1394.0,1394.0,1394.0,1394.0,1394.0,1394.0,1394.0,1394.0,1394.0,1394.0
12,132011.0,38.0,1022.0,1022.0,1022.0,1022.0,1022.0,1022.0,1022.0,1022.0,...,1022.0,1022.0,1022.0,1022.0,1022.0,1022.0,1022.0,1022.0,1022.0,1022.0
13,361253.0,38.0,659.0,659.0,659.0,659.0,659.0,659.0,659.0,659.0,...,659.0,659.0,659.0,659.0,659.0,659.0,659.0,659.0,659.0,659.0
14,129751.0,38.0,1116.0,1116.0,1116.0,1116.0,1116.0,1116.0,1116.0,1116.0,...,1116.0,1116.0,1116.0,1116.0,1116.0,1116.0,1116.0,1116.0,1116.0,1116.0
15,140849.0,38.0,1424.0,1424.0,1424.0,1424.0,1424.0,1424.0,1424.0,1424.0,...,1424.0,1424.0,1424.0,1424.0,1424.0,1424.0,1424.0,1424.0,1424.0,1424.0
16,243758.0,38.0,843.0,843.0,843.0,843.0,843.0,843.0,843.0,843.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,121975.0,38.0,756.0,756.0,756.0,756.0,756.0,756.0,756.0,756.0,...,756.0,756.0,756.0,756.0,756.0,756.0,756.0,756.0,756.0,756.0
18,343436.0,38.0,1059.0,1059.0,1059.0,1059.0,1059.0,1059.0,1059.0,1059.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,329689.0,38.0,1361.0,1361.0,1361.0,1361.0,1361.0,1361.0,1361.0,1361.0,...,1361.0,1361.0,1361.0,1361.0,1361.0,1361.0,1361.0,1361.0,1361.0,1361.0
20,347773.0,38.0,926.0,926.0,926.0,926.0,926.0,926.0,926.0,926.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,136707.0,38.0,1476.0,1476.0,1476.0,1476.0,1476.0,1476.0,1476.0,1476.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,415639.0,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,671.0,671.0,671.0,671.0,671.0,671.0,671.0,671.0,671.0,671.0
23,323169.0,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1279.0,1279.0,1279.0,1279.0,1279.0,1279.0,1279.0,1279.0,1279.0,1279.0
24,280720.0,38.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,823.0,823.0,823.0,823.0,823.0,823.0,823.0,823.0,823.0,823.0
25,419916.0,38.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,807.0,807.0,807.0,807.0,807.0,807.0,807.0,807.0,807.0,807.0
26,419915.0,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1331.0,1331.0,1331.0,1331.0,1331.0,1331.0,1331.0,1331.0,1331.0,1331.0
27,392643.0,38.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1166.0,1166.0,1166.0,1166.0,1166.0,1166.0,1166.0,1166.0,1166.0,1166.0
28,90966.0,38.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1193.0,1193.0,1193.0,1193.0,1193.0,1193.0,1193.0,1193.0,1193.0,1193.0

In [106]:
timeline[["29","30", "31", "32"]]

        29      30      31      32
0    748.0   748.0   748.0   748.0
1   1425.0  1425.0  1425.0  1425.0
2   1010.0  1010.0  1010.0  1010.0
3   1179.0  1179.0  1179.0  1179.0
4   1430.0  1430.0  1430.0  1430.0
5   1082.0  1082.0  1082.0  1082.0
6    988.0   988.0     NaN     NaN
7    837.0   837.0   837.0   837.0
8   1048.0  1048.0  1048.0  1048.0
9    974.0   974.0   974.0   974.0
10   607.0   607.0   607.0   607.0
11  1394.0  1394.0  1394.0  1394.0
12  1022.0  1022.0  1022.0  1022.0
13   659.0   659.0   659.0   659.0
14  1116.0  1116.0  1116.0  1116.0
15  1424.0  1424.0  1424.0  1424.0
16   843.0   843.0   843.0   843.0
17   756.0   756.0   756.0   756.0
18  1059.0  1059.0  1059.0  1059.0
19  1361.0  1361.0  1361.0  1361.0
20   926.0   926.0   926.0   926.0
21  1476.0  1476.0  1476.0  1476.0
22     NaN     NaN   671.0   671.0
23     NaN     NaN     NaN     NaN
24     NaN     NaN     NaN     NaN
25     NaN     NaN     NaN     NaN
26     NaN     NaN     NaN     NaN
27     NaN     NaN     NaN     NaN
28     NaN     NaN     NaN     NaN